blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/jkaberg/hass-byd-vehicle/discussions
    about: Please use Discussions for how-to questions and general support.
