fetch_realtime:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: byd_vehicle

fetch_gps:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: byd_vehicle

fetch_hvac:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: byd_vehicle

fetch_charging:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: byd_vehicle

fetch_energy:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: byd_vehicle
